---
title: "Tidy Data"
output: github_document
---

```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

This document will show how to tidy data.

## Pivot Longer

This needs to go from wide to long format. 

```{r}
pulse_df <- 
  read_sas("Data_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()  %>% 
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  ) %>% 
  relocate(id, visit)
``` 


```{r}
litters_df <- 
  read_csv("Data_examples/FAS_litters.csv", na = c("NA", ".", "")) %>%
  janitor::clean_names() %>%
  pivot_longer(
    cols = gd0_weight:gd18_weight , 
    names_to = "gd_time",
    values_to = "weight"
  ) %>% 
  mutate(
    gd_time = case_match(
      gd_time, 
      "gd0_weight" ~ 0, 
      "gd18_weight" ~ 18
  ))
```


## Pivot Wider 

```{r}
analysis_df <-
  tibble(
    group = c("treatment", "treatment", "control", "control"), 
    time = c("pre", "post", "pre", "post"),
    mean = c(4,10,4.2, 5)
  )
```

Pivot wider for human readability 

```{r}
analysis_df %>% 
  pivot_wider(
    names_from = time,
    values_from = mean
  ) %>% 
  knitr::kable()
```



